<?php

/**
 * 路由 URI => 细粒度菜单权限（menu.nav.*），与侧栏叶子一致；用于路由门禁 OR 旧 menu.*。
 */
class RouteMenuNavMap
{
    /**
     * @return list<string>
     */
    public static function menuNavKeysForUri(string $uri): array
    {
        static $map = [
            '/calendar/create' => ['menu.nav.calendar.create'],
            '/calendar/events' => ['menu.nav.calendar.events'],
            '/calendar/event-status' => ['menu.nav.calendar.events'],
            '/calendar/event-status-logs' => ['menu.nav.calendar.events'],
            '/dispatch' => ['menu.nav.dispatch.orders'],
            '/dispatch/delivery-pod-photo' => ['menu.nav.dispatch.ops.driver'],
            '/dispatch/order-import' => ['menu.nav.dispatch.order_import'],
            '/dispatch/package-ops' => ['menu.nav.dispatch.package_ops'],
            '/dispatch/forwarding/packages' => ['menu.nav.dispatch.forwarding.packages'],
            '/dispatch/forwarding/customers' => ['menu.nav.dispatch.forwarding.customers'],
            '/dispatch/forwarding/records' => ['menu.nav.dispatch.forwarding.records'],
            '/dispatch/forwarding/voucher/view' => ['menu.nav.dispatch.forwarding.packages'],
            '/dispatch/consigning-clients' => ['menu.nav.dispatch.consigning_clients'],
            '/dispatch/delivery-customers' => ['menu.nav.dispatch.delivery_customers'],
            '/dispatch/waybills' => ['menu.nav.dispatch.orders'],
            '/dispatch/ops/delivery-list' => ['menu.nav.dispatch.ops.delivery_list'],
            '/dispatch/ops/binding-list' => ['menu.nav.dispatch.ops.binding_list'],
            '/dispatch/ops/create-delivery' => ['menu.nav.dispatch.ops.create_delivery'],
            '/dispatch/ops/delivery-docs' => ['menu.nav.dispatch.ops.preliminary_docs'],
            '/dispatch/ops/formal-delivery-docs' => ['menu.nav.dispatch.ops.formal_docs'],
            '/dispatch/ops/delivery-pick-sheets' => ['menu.nav.dispatch.ops.pick_sheets'],
            '/dispatch/ops/driver-deliveries' => ['menu.nav.dispatch.ops.driver'],
            '/dispatch/driver/my-deliveries' => ['menu.nav.dispatch.ops.driver'],
            '/dispatch/driver/run' => ['menu.nav.dispatch.ops.driver'],
            '/dispatch/driver/pod-precheck' => ['menu.nav.dispatch.ops.driver'],
            '/dispatch/driver/pod-upload' => ['menu.nav.dispatch.ops.driver'],
            '/dispatch/qz/certificate' => ['menu.nav.dispatch.ops.pick_sheets', 'menu.nav.dispatch.ops.formal_docs'],
            '/dispatch/qz/sign' => ['menu.nav.dispatch.ops.pick_sheets', 'menu.nav.dispatch.ops.formal_docs'],
            '/dispatch/accounting/list' => ['menu.nav.dispatch.accounting.list'],
            '/dispatch/arrival-label-html' => ['menu.nav.dispatch.package_ops', 'menu.nav.dispatch.orders'],
            '/dispatch/arrival-label-pdf' => ['menu.nav.dispatch.package_ops', 'menu.nav.dispatch.orders'],
            '/uda/issues/list' => ['menu.nav.uda.issues.list'],
            '/uda/issues/create' => ['menu.nav.uda.issues.create'],
            '/uda/issues/handle-methods' => ['menu.nav.uda.issues.handle_methods'],
            '/uda/issues/locations' => ['menu.nav.uda.issues.locations'],
            '/uda/issues/reasons' => ['menu.nav.uda.issues.reasons'],
            '/uda/express/query' => ['menu.nav.uda.express.query'],
            '/uda/express/receive' => ['menu.nav.uda.express.receive'],
            '/uda/express/forward-packages' => ['menu.nav.uda.express.forward_packages'],
            '/uda/express/forward-query' => ['menu.nav.uda.express.forward_query'],
            '/uda/express/forward-voucher/view' => ['menu.nav.uda.express.forward_packages'],
            '/uda/batches/list' => ['menu.nav.uda.batches.list'],
            '/uda/batches/create' => ['menu.nav.uda.batches.create'],
            '/uda/batches/waybill-check' => ['menu.nav.uda.batches.list', 'menu.nav.uda.batches.create'],
            '/uda/batches/edit' => ['menu.nav.uda.batches.list'],
            '/uda/batches/packing-list-export' => ['menu.nav.uda.batches.list'],
            '/uda/warehouse/bundles' => ['menu.nav.uda.warehouse.bundles'],
            '/uda/warehouse/create-bundle' => ['menu.nav.uda.warehouse.create_bundle'],
            '/uda/warehouse/batch-view' => ['menu.nav.uda.warehouse.bundles'],
            '/uda/warehouse/batch-edit' => ['menu.nav.uda.warehouse.bundles'],
            '/uda/warehouse/batch-export' => ['menu.nav.uda.warehouse.bundles'],
            '/uda/warehouse/import-template' => ['menu.nav.uda.warehouse.bundles'],
            '/warehouse' => ['menu.nav.warehouse.root'],
            '/finance/transactions/create' => ['menu.nav.finance.transactions.create'],
            '/finance/transactions/list' => ['menu.nav.finance.transactions.list'],
            '/finance/transactions/edit' => ['menu.nav.finance.transactions.list'],
            '/finance/payables/create' => ['menu.nav.finance.payables.create'],
            '/finance/payables/list' => ['menu.nav.finance.payables.list'],
            '/finance/payables/settle' => ['menu.nav.finance.payables.list'],
            '/finance/receivables/create' => ['menu.nav.finance.receivables.create'],
            '/finance/receivables/list' => ['menu.nav.finance.receivables.list'],
            '/finance/receivables/settle' => ['menu.nav.finance.receivables.list'],
            '/finance/voucher/view' => ['menu.nav.finance.transactions.list', 'menu.nav.finance.payables.list', 'menu.nav.finance.receivables.list'],
            '/finance/accounts' => ['menu.nav.finance.accounts'],
            '/finance/categories' => ['menu.nav.finance.categories'],
            '/finance/parties' => ['menu.nav.finance.parties'],
            '/finance/reports/overview' => ['menu.nav.finance.reports'],
            '/finance/reports/detail' => ['menu.nav.finance.reports'],
            '/finance/reports/export' => ['menu.nav.finance.reports'],
            '/finance/ar/customers' => ['menu.nav.finance.ar.customers'],
            '/finance/ar/billing-schemes' => ['menu.nav.finance.ar.billing_schemes'],
            '/finance/ar/charges/create' => ['menu.nav.finance.ar.charges.create'],
            '/finance/ar/charges/options' => ['menu.nav.finance.ar.charges.create', 'menu.nav.finance.ar.charges.list'],
            '/finance/ar/charges/list' => ['menu.nav.finance.ar.charges.list'],
            '/finance/ar/invoices/list' => ['menu.nav.finance.ar.invoices'],
            '/finance/ar/invoices/view' => ['menu.nav.finance.ar.invoices'],
            '/finance/ar/invoices/export-unpaid' => ['menu.nav.finance.ar.invoices'],
            '/finance/ar/invoices/print-unpaid' => ['menu.nav.finance.ar.invoices'],
            '/finance/ar/ledger' => ['menu.nav.finance.ar.ledger'],
            '/system/users' => ['menu.users'],
            '/system/roles' => ['menu.roles'],
            '/system/permissions' => ['menu.nav.system.permissions_page', 'menu.nav.system.permissions_action', 'menu.permissions'],
            '/system/notifications' => ['menu.notifications'],
            '/system/logs' => ['menu.logs'],
            '/notifications/live' => ['menu.notifications'],
            '/notifications/mark-read' => ['menu.notifications'],
        ];
        return $map[$uri] ?? [];
    }
}
