ALTER TABLE users
    ADD COLUMN IF NOT EXISTS phone VARCHAR(40) DEFAULT NULL AFTER full_name,
    ADD COLUMN IF NOT EXISTS wechat VARCHAR(80) DEFAULT NULL AFTER phone,
    ADD COLUMN IF NOT EXISTS line_id VARCHAR(80) DEFAULT NULL AFTER wechat;
